version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - "> 27.0.5, < 27.1"
  - dependency-name: "@gnosis.pm/solidity-data-structures"
    versions:
    - "> 1.2.4"
  - dependency-name: "@gnosis.pm/util-contracts"
    versions:
    - ">= 3.a, < 4"
  - dependency-name: "@openzeppelin/contracts"
    versions:
    - ">= 3.a, < 4"
  - dependency-name: openzeppelin-solidity
    versions:
    - ">= 3.a, < 4"
  - dependency-name: truffle
    versions:
    - "> 5.1.49, < 5.2"
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.4.0
    - 31.6.0
    - 32.0.0
    - 32.0.2
    - 32.1.0
    - 32.1.1
    - 32.2.0
    - 32.3.1
    - 32.3.2
  - dependency-name: synthetix-js
    versions:
    - 2.37.0
    - 2.37.1
    - 2.37.2
    - 2.39.1
    - 2.39.2
    - 2.39.3
    - 2.42.1
  - dependency-name: truffle
    versions:
    - 5.3.0
    - 5.3.1
    - 5.3.2
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.24.0
  - dependency-name: "@truffle/contract"
    versions:
    - 4.3.10
    - 4.3.11
    - 4.3.13
    - 4.3.5
    - 4.3.7
    - 4.3.8
    - 4.3.9
  - dependency-name: eslint-plugin-no-only-tests
    versions:
    - 2.5.0
  - dependency-name: "@truffle/artifactor"
    versions:
    - 4.0.101
    - 4.0.93
    - 4.0.95
    - 4.0.96
    - 4.0.97
    - 4.0.98
    - 4.0.99
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: ethereumjs-util
    versions:
    - 7.0.8
    - 7.0.9
  - dependency-name: truffle-plugin-verify
    versions:
    - 0.5.5
    - 0.5.6
  - dependency-name: eth-gas-reporter
    versions:
    - 0.2.21
  rebase-strategy: disabled
